image: node:alpine

stages:
  - init
  - build

cache:
  paths:
    - node_modules/

install:
  stage: init
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

lint:
  stage: build
  script: npm run lint

build:
  stage: build
  script: 
    - npm rebuild node-sass
    - npm run build