image: node:8

cache:
  key: ${CI_JOB_NAME}
  paths:
    - .cache/
    - .npm_cache

stages:
  - init
  - build

install:
  stage: init
  image: node:8
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 2 weeks
  only:
    changes:
      - package.json
      - package-lock.json

build_client:
  stage: build
  image: node:8
  script: 
    - npm run lint
    - npm rebuild node-sass
    - npm run build:client
  artifacts:
    paths:
      - build/client
      - server
      - shared
      - package.json
      - package-lock.json

  